[project]
name = "swiss-rail-punctuality"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "yutiime", email = "y.demirel467@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "duckdb>=1.5.5",
]

[project.scripts]
swiss-rail-punctuality = "swiss_rail_punctuality:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ruff>=0.16.8",
]
